language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-google_apis-android-23

before_script:
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a --tag google_apis
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
   - ./gradlew connectedAndroidTest coveralls