language: android

jdk: oraclejdk8

env:
 global:
 - ANDROID_API=27
 - EMULATOR_API=22
 - ANDROID_BUILD_TOOLS=25.0.3
 - ADB_INSTALL_TIMEOUT=5

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL

before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a -c 32M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
   - ./gradlew connectedAndroidTest coveralls